### ISSUE TITLE
Any Async support?

### ISSUE THREAD

**Issue by CaiusJard** [SoftCircuits/CsvParser#1]
I was hoping to use SC.CP to read from a stream in a blazor app, but "synchronous reads are not supported" - just wondering if they're imminent, planned, whether I should patch them in or switch parser?

**Comment by SoftCircuits** [comment]
Sorry I never saw this. You probably found another solution but just to reply:

I would like to add async support but the base methods accept a string array by reference and you cannot pass arguments by reference using async. So it may require changing the method signature. So it isn't straight forward but I'm looking into this.

**Comment by SoftCircuits** [comment]
Version 3.5.0 will have asynchronous support.
