### ISSUE TITLE
Reading unmapped columns 

### ISSUE THREAD

**Issue by ghost** [SoftCircuits/CsvParser#3]
While using `MapColumns()` and `CsvReader<T>` is it possible to access the columns that are not explicitly mapped but are not excluded either? There is no apparent way to do that. I would like to populate a `Dictionary<string, string>`with column name/column value pairs for such columns.

If we switch to use `CsvReader.ReadRow()` we throw away all the nice things we get with column mappings.

The parser and most constructs seem heavily locked down by private/internal modifiers. Impossible to inherit CsvReader since ColumnsInfo property is private, the ColumnInfo class itself is internal too. Pretty much impossible to extend anything..

**Comment by SoftCircuits** [comment]
If you're using the `CsvReader<T>` class, you can get the raw column values for the current row via the `Columns` property.

And I don't understand how being able to access `ColumnInfo` would help as it wouldn't contain any information about unmapped columns.
