### ISSUE TITLE
Total nbr of rows property?

### ISSUE THREAD

**Issue by tekeroth-snapcode** [SoftCircuits/CsvParser#4]
I would like to have a property that returns the number of rows in the CSV file. Currently, I can only iterate through them, but I have no idea when Im done, since I cannot get a value of how many rows are in the file.

Is that fixable?

Thanks!

**Comment by SoftCircuits** [comment]
This would be a feature request, not a fix. The library returns a value that indicates if the end of the file has been reached. See the documentation for samples.

There is no direct way to get the number of lines in a text file. You would have to load and scan the entire file. This would be outside the scope of what the CsvParser library does.
